
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CWS.Infrastructure.Concrete
{
using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using CWS.Domain.Abstract;

		



/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="CWSModel", Name="Menu")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class Menu : EntityObject , IMenu
{
    #region Factory Method

    /// <summary>
    /// Create a new Menu object.
    /// </summary>
    /// <param name="id">Initial value of the Id property.</param>
    /// <param name="description">Initial value of the Description property.</param>
    /// <param name="displayText">Initial value of the DisplayText property.</param>
    /// <param name="sortOrder">Initial value of the SortOrder property.</param>
    /// <param name="dateCreated">Initial value of the DateCreated property.</param>
    /// <param name="active">Initial value of the Active property.</param>
    public static Menu CreateMenu(global::System.Int32 id, global::System.String description, global::System.String displayText, global::System.Int16 sortOrder, global::System.DateTime dateCreated, global::System.Boolean active)
    {
        Menu menu = new Menu();
        menu.Id = id;
        menu.Description = description;
        menu.DisplayText = displayText;
        menu.SortOrder = sortOrder;
        menu.DateCreated = dateCreated;
        menu.Active = active;
        return menu;
    }

    #endregion
#region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 Id
    {
        get
        {
            return _Id;
        }
        set
        {
            if (_Id != value)
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
    }
    private global::System.Int32 _Id;
    partial void OnIdChanging(global::System.Int32 value);
    partial void OnIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String Description
    {
        get
        {
            return _Description;
        }
        set
        {
            OnDescriptionChanging(value);
            ReportPropertyChanging("Description");
            _Description = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("Description");
            OnDescriptionChanged();
        }
    }
    private global::System.String _Description;
    partial void OnDescriptionChanging(global::System.String value);
    partial void OnDescriptionChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String DisplayText
    {
        get
        {
            return _DisplayText;
        }
        set
        {
            OnDisplayTextChanging(value);
            ReportPropertyChanging("DisplayText");
            _DisplayText = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("DisplayText");
            OnDisplayTextChanged();
        }
    }
    private global::System.String _DisplayText;
    partial void OnDisplayTextChanging(global::System.String value);
    partial void OnDisplayTextChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> MenuTypeId
    {
        get
        {
            return _MenuTypeId;
        }
        set
        {
            OnMenuTypeIdChanging(value);
            ReportPropertyChanging("MenuTypeId");
            _MenuTypeId = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("MenuTypeId");
            OnMenuTypeIdChanged();
        }
    }
    private Nullable<global::System.Int32> _MenuTypeId;
    partial void OnMenuTypeIdChanging(Nullable<global::System.Int32> value);
    partial void OnMenuTypeIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String Action
    {
        get
        {
            return _Action;
        }
        set
        {
            OnActionChanging(value);
            ReportPropertyChanging("Action");
            _Action = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("Action");
            OnActionChanged();
        }
    }
    private global::System.String _Action;
    partial void OnActionChanging(global::System.String value);
    partial void OnActionChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String CSSClass
    {
        get
        {
            return _CSSClass;
        }
        set
        {
            OnCSSClassChanging(value);
            ReportPropertyChanging("CSSClass");
            _CSSClass = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("CSSClass");
            OnCSSClassChanged();
        }
    }
    private global::System.String _CSSClass;
    partial void OnCSSClassChanging(global::System.String value);
    partial void OnCSSClassChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String ImageUrl
    {
        get
        {
            return _ImageUrl;
        }
        set
        {
            OnImageUrlChanging(value);
            ReportPropertyChanging("ImageUrl");
            _ImageUrl = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("ImageUrl");
            OnImageUrlChanged();
        }
    }
    private global::System.String _ImageUrl;
    partial void OnImageUrlChanging(global::System.String value);
    partial void OnImageUrlChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> ParentId
    {
        get
        {
            return _ParentId;
        }
        set
        {
            OnParentIdChanging(value);
            ReportPropertyChanging("ParentId");
            _ParentId = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("ParentId");
            OnParentIdChanged();
        }
    }
    private Nullable<global::System.Int32> _ParentId;
    partial void OnParentIdChanging(Nullable<global::System.Int32> value);
    partial void OnParentIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int16 SortOrder
    {
        get
        {
            return _SortOrder;
        }
        set
        {
            OnSortOrderChanging(value);
            ReportPropertyChanging("SortOrder");
            _SortOrder = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("SortOrder");
            OnSortOrderChanged();
        }
    }
    private global::System.Int16 _SortOrder;
    partial void OnSortOrderChanging(global::System.Int16 value);
    partial void OnSortOrderChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.DateTime DateCreated
    {
        get
        {
            return _DateCreated;
        }
        set
        {
            OnDateCreatedChanging(value);
            ReportPropertyChanging("DateCreated");
            _DateCreated = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DateCreated");
            OnDateCreatedChanged();
        }
    }
    private global::System.DateTime _DateCreated;
    partial void OnDateCreatedChanging(global::System.DateTime value);
    partial void OnDateCreatedChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> DateModified
    {
        get
        {
            return _DateModified;
        }
        set
        {
            OnDateModifiedChanging(value);
            ReportPropertyChanging("DateModified");
            _DateModified = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DateModified");
            OnDateModifiedChanged();
        }
    }
    private Nullable<global::System.DateTime> _DateModified;
    partial void OnDateModifiedChanging(Nullable<global::System.DateTime> value);
    partial void OnDateModifiedChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.DateTime> DateDeactivated
    {
        get
        {
            return _DateDeactivated;
        }
        set
        {
            OnDateDeactivatedChanging(value);
            ReportPropertyChanging("DateDeactivated");
            _DateDeactivated = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DateDeactivated");
            OnDateDeactivatedChanged();
        }
    }
    private Nullable<global::System.DateTime> _DateDeactivated;
    partial void OnDateDeactivatedChanging(Nullable<global::System.DateTime> value);
    partial void OnDateDeactivatedChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Boolean Active
    {
        get
        {
            return _Active;
        }
        set
        {
            OnActiveChanging(value);
            ReportPropertyChanging("Active");
            _Active = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("Active");
            OnActiveChanged();
        }
    }
    private global::System.Boolean _Active;
    partial void OnActiveChanging(global::System.Boolean value);
    partial void OnActiveChanged();

#endregion

#region Navigation Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmRelationshipNavigationPropertyAttribute("CWSModel", "FK_Menu_MenuType", "MenuType")]
    public MenuType MenuType
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuType>("CWSModel.FK_Menu_MenuType", "MenuType").Value;
        }
        set
        {
            ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuType>("CWSModel.FK_Menu_MenuType", "MenuType").Value = value;
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[BrowsableAttribute(false)]
    //[DataMemberAttribute()]
    public EntityReference<MenuType> MenuTypeReference
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuType>("CWSModel.FK_Menu_MenuType", "MenuType");
        }
        set
        {
            if ((value != null))
            {
                ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MenuType>("CWSModel.FK_Menu_MenuType", "MenuType", value);
            }
        }
    } //test2

#endregion
}//test
		



/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="CWSModel", Name="MenuPattern")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class MenuPattern : EntityObject , IMenuPattern
{
    #region Factory Method

    /// <summary>
    /// Create a new MenuPattern object.
    /// </summary>
    /// <param name="id">Initial value of the Id property.</param>
    /// <param name="description">Initial value of the Description property.</param>
    /// <param name="horizontal">Initial value of the Horizontal property.</param>
    public static MenuPattern CreateMenuPattern(global::System.Int32 id, global::System.String description, global::System.Boolean horizontal)
    {
        MenuPattern menuPattern = new MenuPattern();
        menuPattern.Id = id;
        menuPattern.Description = description;
        menuPattern.Horizontal = horizontal;
        return menuPattern;
    }

    #endregion
#region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 Id
    {
        get
        {
            return _Id;
        }
        set
        {
            if (_Id != value)
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
    }
    private global::System.Int32 _Id;
    partial void OnIdChanging(global::System.Int32 value);
    partial void OnIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String Description
    {
        get
        {
            return _Description;
        }
        set
        {
            OnDescriptionChanging(value);
            ReportPropertyChanging("Description");
            _Description = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("Description");
            OnDescriptionChanged();
        }
    }
    private global::System.String _Description;
    partial void OnDescriptionChanging(global::System.String value);
    partial void OnDescriptionChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Boolean Horizontal
    {
        get
        {
            return _Horizontal;
        }
        set
        {
            OnHorizontalChanging(value);
            ReportPropertyChanging("Horizontal");
            _Horizontal = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("Horizontal");
            OnHorizontalChanged();
        }
    }
    private global::System.Boolean _Horizontal;
    partial void OnHorizontalChanging(global::System.Boolean value);
    partial void OnHorizontalChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> Columns
    {
        get
        {
            return _Columns;
        }
        set
        {
            OnColumnsChanging(value);
            ReportPropertyChanging("Columns");
            _Columns = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("Columns");
            OnColumnsChanged();
        }
    }
    private Nullable<global::System.Int32> _Columns;
    partial void OnColumnsChanging(Nullable<global::System.Int32> value);
    partial void OnColumnsChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public Nullable<global::System.Int32> Rows
    {
        get
        {
            return _Rows;
        }
        set
        {
            OnRowsChanging(value);
            ReportPropertyChanging("Rows");
            _Rows = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("Rows");
            OnRowsChanged();
        }
    }
    private Nullable<global::System.Int32> _Rows;
    partial void OnRowsChanging(Nullable<global::System.Int32> value);
    partial void OnRowsChanged();

#endregion

#region Navigation Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmRelationshipNavigationPropertyAttribute("CWSModel", "FK_MenuType_MenuPattern", "MenuType")]
    public EntityCollection<MenuType> MenuType
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MenuType>("CWSModel.FK_MenuType_MenuPattern", "MenuType");
        }
        set
        {
            if ((value != null))
            {
                ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MenuType>("CWSModel.FK_MenuType_MenuPattern", "MenuType", value);
            }
        }
    }

#endregion
}//test
		



/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="CWSModel", Name="MenuType")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class MenuType : EntityObject , IMenuType
{
    #region Factory Method

    /// <summary>
    /// Create a new MenuType object.
    /// </summary>
    /// <param name="id">Initial value of the Id property.</param>
    /// <param name="description">Initial value of the Description property.</param>
    /// <param name="menuPatternId">Initial value of the MenuPatternId property.</param>
    public static MenuType CreateMenuType(global::System.Int32 id, global::System.String description, global::System.Int32 menuPatternId)
    {
        MenuType menuType = new MenuType();
        menuType.Id = id;
        menuType.Description = description;
        menuType.MenuPatternId = menuPatternId;
        return menuType;
    }

    #endregion
#region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 Id
    {
        get
        {
            return _Id;
        }
        set
        {
            if (_Id != value)
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
    }
    private global::System.Int32 _Id;
    partial void OnIdChanging(global::System.Int32 value);
    partial void OnIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String Description
    {
        get
        {
            return _Description;
        }
        set
        {
            OnDescriptionChanging(value);
            ReportPropertyChanging("Description");
            _Description = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("Description");
            OnDescriptionChanged();
        }
    }
    private global::System.String _Description;
    partial void OnDescriptionChanging(global::System.String value);
    partial void OnDescriptionChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String CSSClass
    {
        get
        {
            return _CSSClass;
        }
        set
        {
            OnCSSClassChanging(value);
            ReportPropertyChanging("CSSClass");
            _CSSClass = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("CSSClass");
            OnCSSClassChanged();
        }
    }
    private global::System.String _CSSClass;
    partial void OnCSSClassChanging(global::System.String value);
    partial void OnCSSClassChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Int32 MenuPatternId
    {
        get
        {
            return _MenuPatternId;
        }
        set
        {
            OnMenuPatternIdChanging(value);
            ReportPropertyChanging("MenuPatternId");
            _MenuPatternId = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("MenuPatternId");
            OnMenuPatternIdChanged();
        }
    }
    private global::System.Int32 _MenuPatternId;
    partial void OnMenuPatternIdChanging(global::System.Int32 value);
    partial void OnMenuPatternIdChanged();

#endregion

#region Navigation Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmRelationshipNavigationPropertyAttribute("CWSModel", "FK_Menu_MenuType", "Menu")]
    public EntityCollection<Menu> Menu
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Menu>("CWSModel.FK_Menu_MenuType", "Menu");
        }
        set
        {
            if ((value != null))
            {
                ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Menu>("CWSModel.FK_Menu_MenuType", "Menu", value);
            }
        }
    }

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmRelationshipNavigationPropertyAttribute("CWSModel", "FK_MenuType_MenuPattern", "MenuPattern")]
    public MenuPattern MenuPattern
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuPattern>("CWSModel.FK_MenuType_MenuPattern", "MenuPattern").Value;
        }
        set
        {
            ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuPattern>("CWSModel.FK_MenuType_MenuPattern", "MenuPattern").Value = value;
        }
    }
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    //[BrowsableAttribute(false)]
    //[DataMemberAttribute()]
    public EntityReference<MenuPattern> MenuPatternReference
    {
        get
        {
            return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MenuPattern>("CWSModel.FK_MenuType_MenuPattern", "MenuPattern");
        }
        set
        {
            if ((value != null))
            {
                ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MenuPattern>("CWSModel.FK_MenuType_MenuPattern", "MenuPattern", value);
            }
        }
    } //test2

#endregion
}//test
		



/// <summary>
/// No Metadata Documentation available.
/// </summary>
[EdmEntityTypeAttribute(NamespaceName="CWSModel", Name="User")]
[Serializable()]
[DataContractAttribute(IsReference=true)]
public partial class User : EntityObject , IUser
{
    #region Factory Method

    /// <summary>
    /// Create a new User object.
    /// </summary>
    /// <param name="id">Initial value of the Id property.</param>
    /// <param name="userName">Initial value of the UserName property.</param>
    /// <param name="firstName">Initial value of the FirstName property.</param>
    /// <param name="lastName">Initial value of the LastName property.</param>
    /// <param name="email">Initial value of the Email property.</param>
    /// <param name="dateCreated">Initial value of the DateCreated property.</param>
    /// <param name="dateModified">Initial value of the DateModified property.</param>
    /// <param name="active">Initial value of the Active property.</param>
    public static User CreateUser(global::System.Guid id, global::System.String userName, global::System.String firstName, global::System.String lastName, global::System.String email, global::System.DateTime dateCreated, global::System.DateTime dateModified, global::System.Boolean active)
    {
        User user = new User();
        user.Id = id;
        user.UserName = userName;
        user.FirstName = firstName;
        user.LastName = lastName;
        user.Email = email;
        user.DateCreated = dateCreated;
        user.DateModified = dateModified;
        user.Active = active;
        return user;
    }

    #endregion
#region Primitive Properties

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Guid Id
    {
        get
        {
            return _Id;
        }
        set
        {
            if (_Id != value)
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
    }
    private global::System.Guid _Id;
    partial void OnIdChanging(global::System.Guid value);
    partial void OnIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String UserName
    {
        get
        {
            return _UserName;
        }
        set
        {
            OnUserNameChanging(value);
            ReportPropertyChanging("UserName");
            _UserName = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("UserName");
            OnUserNameChanged();
        }
    }
    private global::System.String _UserName;
    partial void OnUserNameChanging(global::System.String value);
    partial void OnUserNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String FirstName
    {
        get
        {
            return _FirstName;
        }
        set
        {
            OnFirstNameChanging(value);
            ReportPropertyChanging("FirstName");
            _FirstName = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("FirstName");
            OnFirstNameChanged();
        }
    }
    private global::System.String _FirstName;
    partial void OnFirstNameChanging(global::System.String value);
    partial void OnFirstNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String LastName
    {
        get
        {
            return _LastName;
        }
        set
        {
            OnLastNameChanging(value);
            ReportPropertyChanging("LastName");
            _LastName = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("LastName");
            OnLastNameChanged();
        }
    }
    private global::System.String _LastName;
    partial void OnLastNameChanging(global::System.String value);
    partial void OnLastNameChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.String Email
    {
        get
        {
            return _Email;
        }
        set
        {
            OnEmailChanging(value);
            ReportPropertyChanging("Email");
            _Email = StructuralObject.SetValidValue(value, false);
            ReportPropertyChanged("Email");
            OnEmailChanged();
        }
    }
    private global::System.String _Email;
    partial void OnEmailChanging(global::System.String value);
    partial void OnEmailChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
    [DataMemberAttribute()]
    public global::System.String UserStatusId
    {
        get
        {
            return _UserStatusId;
        }
        set
        {
            OnUserStatusIdChanging(value);
            ReportPropertyChanging("UserStatusId");
            _UserStatusId = StructuralObject.SetValidValue(value, true);
            ReportPropertyChanged("UserStatusId");
            OnUserStatusIdChanged();
        }
    }
    private global::System.String _UserStatusId;
    partial void OnUserStatusIdChanging(global::System.String value);
    partial void OnUserStatusIdChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.DateTime DateCreated
    {
        get
        {
            return _DateCreated;
        }
        set
        {
            OnDateCreatedChanging(value);
            ReportPropertyChanging("DateCreated");
            _DateCreated = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DateCreated");
            OnDateCreatedChanged();
        }
    }
    private global::System.DateTime _DateCreated;
    partial void OnDateCreatedChanging(global::System.DateTime value);
    partial void OnDateCreatedChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.DateTime DateModified
    {
        get
        {
            return _DateModified;
        }
        set
        {
            OnDateModifiedChanging(value);
            ReportPropertyChanging("DateModified");
            _DateModified = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("DateModified");
            OnDateModifiedChanged();
        }
    }
    private global::System.DateTime _DateModified;
    partial void OnDateModifiedChanging(global::System.DateTime value);
    partial void OnDateModifiedChanged();

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
    [DataMemberAttribute()]
    public global::System.Boolean Active
    {
        get
        {
            return _Active;
        }
        set
        {
            OnActiveChanging(value);
            ReportPropertyChanging("Active");
            _Active = StructuralObject.SetValidValue(value);
            ReportPropertyChanged("Active");
            OnActiveChanged();
        }
    }
    private global::System.Boolean _Active;
    partial void OnActiveChanging(global::System.Boolean value);
    partial void OnActiveChanged();

#endregion

}//test

} //test3
