//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using CWS.Infrastructure.Concrete;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CWSModel", "FK_Menu_MenuType", "MenuType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CWS.Infrastructure.Concrete.MenuType), "Menu", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CWS.Infrastructure.Concrete.Menu), true)]
[assembly: EdmRelationshipAttribute("CWSModel", "FK_MenuType_MenuPattern", "MenuPattern", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CWS.Infrastructure.Concrete.MenuPattern), "MenuType", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CWS.Infrastructure.Concrete.MenuType), true)]

#endregion

namespace CWS.Infrastructure.Concrete
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CWSContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CWSContext object using the connection string found in the 'CWSContext' section of the application configuration file.
        /// </summary>
        public CWSContext() : base("name=CWSContext", "CWSContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CWSContext object.
        /// </summary>
        public CWSContext(string connectionString) : base(connectionString, "CWSContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CWSContext object.
        /// </summary>
        public CWSContext(EntityConnection connection) : base(connection, "CWSContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Menu> Menu
        {
            get
            {
                if ((_Menu == null))
                {
                    _Menu = base.CreateObjectSet<Menu>("Menu");
                }
                return _Menu;
            }
        }
        private ObjectSet<Menu> _Menu;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuPattern> MenuPattern
        {
            get
            {
                if ((_MenuPattern == null))
                {
                    _MenuPattern = base.CreateObjectSet<MenuPattern>("MenuPattern");
                }
                return _MenuPattern;
            }
        }
        private ObjectSet<MenuPattern> _MenuPattern;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MenuType> MenuType
        {
            get
            {
                if ((_MenuType == null))
                {
                    _MenuType = base.CreateObjectSet<MenuType>("MenuType");
                }
                return _MenuType;
            }
        }
        private ObjectSet<MenuType> _MenuType;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Menu EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenu(Menu menu)
        {
            base.AddObject("Menu", menu);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuPattern EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuPattern(MenuPattern menuPattern)
        {
            base.AddObject("MenuPattern", menuPattern);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MenuType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMenuType(MenuType menuType)
        {
            base.AddObject("MenuType", menuType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion
    }
    

    #endregion
    
}
