//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using DF.Domain.Concrete;


namespace DF.Domain.Abstract
{
    
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IAddress
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Address1
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Address2
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String City
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String State
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String County
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Type
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Zip
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "Dealership_Address", "Dealership")]
         EntityCollection<Dealership> Dealership
        {
            get;
            set;
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Buyer_Address", "Buyer")]
        Buyer Buyer
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Buyer> BuyerReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Lender_Address", "Lender")]
         EntityCollection<Lender> Lender
        {
            get;
            set;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IBuyer
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String SSN
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DOB
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String DL
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DLExpiration
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String DLState
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> ContactId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> AddressId
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Buyer_Address", "Address")]
        Address Address
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Address> AddressReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Buyer_Contact", "Contact")]
        Contact Contact
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Contact> ContactReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Deal_Buyer", "Deal")]
         EntityCollection<Deal> Deal
        {
            get;
            set;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface ICompany
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Description  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String Description
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DateCreated  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.DateTime DateCreated
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DateModified
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DateDeactivated
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> CreatedByUserId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> ModifiedByUserId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> DeactivatedByUserId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Active  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Boolean Active
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Company_User", "User")]
        User User
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<User> UserReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Company_User1", "User")]
        User User1
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<User> User1Reference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Company_User2", "User")]
        User User2
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<User> User2Reference
        {
            get;
            set;
        } //test2

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IContact
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String FirstName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String LastName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Primary  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Boolean Primary
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Phone
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Email
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Fax
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Buyer_Contact", "Buyer")]
        Buyer Buyer
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Buyer> BuyerReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "Dealership_Contact", "Dealership")]
         EntityCollection<Dealership> Dealership
        {
            get;
            set;
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Lender_Contact", "Lender")]
         EntityCollection<Lender> Lender
        {
            get;
            set;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IDeal
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Boolean> Completed
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Boolean> CashDeal
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> SaleDate
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String SalesPerson
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> DealershipId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> LenderId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> BuyerId
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Deal_Buyer", "Buyer")]
        Buyer Buyer
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Buyer> BuyerReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Deal_Dealership", "Dealership")]
        Dealership Dealership
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Dealership> DealershipReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Deal_Lender", "Lender")]
        Lender Lender
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Lender> LenderReference
        {
            get;
            set;
        } //test2

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IDealership
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Name
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String UserName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> AddressID
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> ContactID
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "Dealership_Address", "Address")]
        Address Address
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Address> AddressReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "Dealership_Contact", "Contact")]
        Contact Contact
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Contact> ContactReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Deal_Dealership", "Deal")]
         EntityCollection<Deal> Deal
        {
            get;
            set;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IDocument
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DocumentID  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid DocumentID
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String DocumentName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Required  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Boolean Required
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DocumentBankLenderID  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid DocumentBankLenderID
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> DocumentBankLender_BankLenderID
        {
            get;
            set;        
        }

        #endregion
    
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IInstructions
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="InstructionsID  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid InstructionsID
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Instruction
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="InstructionBankLenderID  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid InstructionBankLenderID
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> InstructionBankLender_BankLenderID
        {
            get;
            set;        
        }

        #endregion
    
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface ILender
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String LenderName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String EIN
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DealershipSplit  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Int32 DealershipSplit
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="BankSplit  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Int32 BankSplit
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Phone
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Fax
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="AddressID  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid AddressID
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="ContactID  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid ContactID
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Lender_Address", "Address")]
        Address Address
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Address> AddressReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Lender_Contact", "Contact")]
        Contact Contact
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Contact> ContactReference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Deal_Lender", "Deal")]
         EntityCollection<Deal> Deal
        {
            get;
            set;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IMenu
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Int32 Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Description  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String Description
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DisplayText  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String DisplayText
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Int32> MenuTypeId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Area
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Controller
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Action
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String CSSClass
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String ImageUrl
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Int32> ParentId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="SortOrder  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Int16 SortOrder
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DateCreated  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.DateTime DateCreated
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DateModified
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DateDeactivated
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Active  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Boolean Active
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Menu_Menu", "Menu1")]
         EntityCollection<Menu> Menu1
        {
            get;
            set;
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Menu_Menu", "Menu")]
        Menu Menu2
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<Menu> Menu2Reference
        {
            get;
            set;
        } //test2
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Menu_MenuType", "MenuType")]
        MenuType MenuType
        {
            get;
            set;
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        EntityReference<MenuType> MenuTypeReference
        {
            get;
            set;
        } //test2

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IMenuType
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Int32 Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Description  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String Description
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Menu_MenuType", "Menu")]
         EntityCollection<Menu> Menu
        {
            get;
            set;
        }

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    
    public interface IUser
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Id  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Guid Id
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="FirstName  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String FirstName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="LastName  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String LastName
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        global::System.String Email
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Description  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.String Description
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="DateCreated  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.DateTime DateCreated
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DateModified
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.DateTime> DateDeactivated
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> CreatedByUserId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> ModifiedByUserId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]	
        Nullable<global::System.Guid> DeactivatedByUserId
        {
            get;
            set;        
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
    		[Required(ErrorMessage="Active  is a required field")]
    	    [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]	
        global::System.Boolean Active
        {
            get;
            set;        
        }

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Company_User", "Company")]
         EntityCollection<Company> Company
        {
            get;
            set;
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Company_User1", "Company")]
         EntityCollection<Company> Company1
        {
            get;
            set;
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmRelationshipNavigationPropertyAttribute("DFModel", "FK_Company_User2", "Company")]
         EntityCollection<Company> Company2
        {
            get;
            set;
        }

        #endregion
    
    }

    #endregion
    
}
